### ISSUE TITLE
typecheck results

### ISSUE THREAD

**Issue by Skjolnir** [DaedalicEntertainment/unreal-coding-conventions#1]
3.1 DO not ("not" not in capital case and not bold)

4.6 DO marks (should be "mark" instead of "marks")

4.7 DO use a non-virtual destructor in final classes have unless they are already derived (minus "have")

9.4 DO NOT not put multiple statements on one line (2nd "not" not needed)

10.2 right example contradicts 11.1 (opening brace not on its own line)

**Comment by npruehs** [comment]
Thanks @Skjolnir :) Fixed in commit 53b1221936cc29b45ab005ae1d494b092da19396 and 60c6a5bacf9c9b0664035be5a0da84f9680fe1bc.
